// Generated by `npm run seed:municipal` (scripts/seed/municipal.ts) from
// src/data/seed/municipalSource.ts. Don't edit by hand; run it again instead.
//
// Four pre-made, signed barangay QRs for the municipal laptop demo: invented,
// de-identified counts for San Isidro Demo (synthetic sample data). Each was
// signed with a key pair made in memory for that run; only the public keys
// are kept, as pairedDevices seed rows. No private key is in this repo.
import type { SampleDevice } from './municipalSource'

export const MUNICIPAL_SAMPLE_EPI_WEEK = '2026-W41'

export const municipalSampleDevices: SampleDevice[] = [
  {
    barangay: 'SID-BGS',
    publicJwk: { kty: 'EC', crv: 'P-256', x: 'ss0x9NQIFOK8qGbi07-rr0EBZaPvVjTLAghk2vmeU-4', y: 'WiPaAjDCfIYnskCOoY8j4SxzIp88pYzll3naxeVQcu4' },
    fingerprint: 'E366-AF1D-6F67-5D0B',
    source: 'seed',
  },
  {
    barangay: 'SID-STN',
    publicJwk: { kty: 'EC', crv: 'P-256', x: 'G3RO7Yif9Qlk_dwb1ORiUxNX4J3AdIBjeoNGXupovs4', y: 'ULDiep2ksUfZ6UoOYoT4OduRZXm2p8P3YGT6epFzZXg' },
    fingerprint: 'D9D9-D243-A53B-1E49',
    source: 'seed',
  },
  {
    barangay: 'SID-MAB',
    publicJwk: { kty: 'EC', crv: 'P-256', x: 'VrmVCWxmh44pXJ9YUhf5wUzVpMUOFsohG6aVniTRUi0', y: '9_xprEbK2JDIvPrhKzLKrh6Ig2byUVwsPOQ6sgjLPV0' },
    fingerprint: 'F0C8-DA19-02BF-07BF',
    source: 'seed',
  },
  {
    barangay: 'SID-RIV',
    publicJwk: { kty: 'EC', crv: 'P-256', x: '2h20cSyBIFNeBlEiFu24dkHuGHvqO3Wlef5abuddPfQ', y: 'JmMZiK0KmCzrQCKtxXFG7EtlPE9f0-YGa2V9sq-hYGQ' },
    fingerprint: '9624-94D4-4FD4-F8A7',
    source: 'seed',
  },
]

export const municipalSampleQrTexts: string[] = [
  'AGP1.eyJ2IjoxLCJtIjoiU0lEIiwiYiI6IlNJRC1CR1MiLCJ3ayI6IjIwMjYtVzQxIiwibiI6MywiZSI6WyI8NSIsNiwxNCwzOCw3MSwxMl0sInciOjY0LCJmIjpbIjw1IiwiPDUiLDddLCJ1Ijo1LCJkIjoxMCwieCI6MCwiciI6MTJ9.Hwnpxvy0-2ZAl9BkyH9JIkG0waaC_reZVmd5L-r_090HVIPBqj0oXbdiyiv6UIMUK69Ku7ahgm4gacj34Utdgw',
  'AGP1.eyJ2IjoxLCJtIjoiU0lEIiwiYiI6IlNJRC1TVE4iLCJ3ayI6IjIwMjYtVzQxIiwibiI6MiwiZSI6WzAsIjw1Iiw2LDE1LDMzLDddLCJ3IjoyNywiZiI6WzAsIjw1IiwiPDUiXSwidSI6Ijw1IiwiZCI6NjAsIngiOjAsInIiOjV9.i2XQTi0JnAVsbKuTSnU0PCfVap9L8wLHWckXa1RxYubI32BTUsWpIsNcyPvx9OcJSWV2_gUDANXgRLhQQOiIww',
  'AGP1.eyJ2IjoxLCJtIjoiU0lEIiwiYiI6IlNJRC1NQUIiLCJ3ayI6IjIwMjYtVzQxIiwibiI6NCwiZSI6WzAsMCwiPDUiLDksMjEsIjw1Il0sInciOjExLCJmIjpbMCwwLDVdLCJ1IjowLCJkIjoyNCwieCI6MCwiciI6Ijw1In0.6Ye-Bri2PnXCIrnBjeL_RdR1E9veSHCc2euJZhubMXh4ou6otOsIRBNm5t8pUSXaleiP4ulGeWIRamrmEfN-BQ',
  'AGP1.eyJ2IjoxLCJtIjoiU0lEIiwiYiI6IlNJRC1SSVYiLCJ3ayI6IjIwMjYtVzQxIiwibiI6MiwiZSI6WzAsMCwwLCI8NSIsIjw1IiwwXSwidyI6Ijw1IiwiZiI6WzAsMCwiPDUiXSwidSI6MCwiZCI6NTAsIngiOjMwLCJyIjowfQ.upaDv816IFh6YMeXZ3aC2IziD7IwE5IMq0QWWLlnZZvw9trixpWPHafBgocZ_Nx21hkHBdwD4gR3-_aFCdwQTQ',
]
