import { createPayload, encodeQr, generateDeviceKeyPair, keyFingerprint, type PublicJwk, type RawCounts } from '../../qr'
import { DEMO_MUNICIPALITY } from '../places'

// The source of the four pre-made barangay QRs for the municipal laptop demo
// (B4 part 2). `npm run seed:municipal` (scripts/seed/municipal.ts) signs these
// counts for one ISO week and writes src/data/seed/municipal.ts.
//
// Everything is invented sample data for the fictional municipality San Isidro
// Demo: de-identified counts only, the kind a barangay phone sends. The story
// the plan should tell: the live Maligaya-D phone becomes the first doctor-team
// destination; Riverside-D has nobody in the watch window
// but holds doxycycline that expires within 6 weeks, so the plan suggests a
// move. Maligaya-D is the live demo phone, paired on stage, so it isn't here.
//
// Each run makes a fresh key pair per barangay in memory (non-extractable, so
// the private key can sign but can never be read out or written anywhere).
// Only the QR texts and the public keys are written.

export const SAMPLE_SEQ_START = 1

export type SampleBarangay = { code: string; seq: number; counts: RawCounts }

export const SAMPLE_BARANGAYS: readonly SampleBarangay[] = [
  {
    // The only pre-made barangay with an active watch; below the live phone.
    code: 'SID-BGS',
    seq: 3,
    counts: {
      exposed: { under2m: 2, m2to12: 6, y1to5: 14, y5to17: 38, y18to59: 71, y60plus: 12 },
      inWatchWindow: 6,
      fastBreathing: { under2m: 0, m2to12: 0, y1to5: 0 },
      urgentReferrals: 0,
      doxyCapsulesOnHand: 10,
      doxyCapsulesExpiring6w: 0,
      clinicianReviewFlags: 12,
    },
  },
  {
    code: 'SID-STN',
    seq: 2,
    counts: {
      exposed: { under2m: 0, m2to12: 2, y1to5: 6, y5to17: 15, y18to59: 33, y60plus: 7 },
      inWatchWindow: 0,
      fastBreathing: { under2m: 0, m2to12: 0, y1to5: 0 },
      urgentReferrals: 0,
      doxyCapsulesOnHand: 60,
      doxyCapsulesExpiring6w: 0,
      clinicianReviewFlags: 5,
    },
  },
  {
    code: 'SID-MAB',
    seq: 4,
    counts: {
      exposed: { under2m: 0, m2to12: 0, y1to5: 3, y5to17: 9, y18to59: 21, y60plus: 4 },
      inWatchWindow: 0,
      fastBreathing: { under2m: 0, m2to12: 0, y1to5: 0 },
      urgentReferrals: 0,
      doxyCapsulesOnHand: 24,
      doxyCapsulesExpiring6w: 0,
      clinicianReviewFlags: 2,
    },
  },
  {
    // Upland: few exposed, but a lot of doxycycline close to expiry.
    code: 'SID-RIV',
    seq: 2,
    counts: {
      exposed: { under2m: 0, m2to12: 0, y1to5: 0, y5to17: 2, y18to59: 3, y60plus: 0 },
      inWatchWindow: 0,
      fastBreathing: { under2m: 0, m2to12: 0, y1to5: 0 },
      urgentReferrals: 0,
      doxyCapsulesOnHand: 50,
      doxyCapsulesExpiring6w: 30,
      clinicianReviewFlags: 0,
    },
  },
]

// One pairedDevices seed row (pairedAt is set when the laptop loads it).
export type SampleDevice = { barangay: string; publicJwk: PublicJwk; fingerprint: string; source: 'seed' }

export type MunicipalSample = { epiWeek: string; devices: SampleDevice[]; qrTexts: string[] }

export async function generateMunicipalSample(epiWeek: string): Promise<MunicipalSample> {
  const devices: SampleDevice[] = []
  const qrTexts: string[] = []
  for (const barangay of SAMPLE_BARANGAYS) {
    const keys = await generateDeviceKeyPair()
    const payload = createPayload({
      municipality: DEMO_MUNICIPALITY.code,
      barangay: barangay.code,
      epiWeek,
      seq: barangay.seq,
      counts: barangay.counts,
    })
    qrTexts.push(await encodeQr(payload, keys.privateKey))
    devices.push({
      barangay: barangay.code,
      publicJwk: keys.publicJwk,
      fingerprint: await keyFingerprint(keys.publicJwk),
      source: 'seed',
    })
  }
  return { epiWeek, devices, qrTexts }
}

// The TypeScript module written to src/data/seed/municipal.ts.
export function renderMunicipalSampleModule(sample: MunicipalSample): string {
  const devices = sample.devices
    .map(
      (device) =>
        `  {\n    barangay: '${device.barangay}',\n` +
        `    publicJwk: { kty: 'EC', crv: 'P-256', x: '${device.publicJwk.x}', y: '${device.publicJwk.y}' },\n` +
        `    fingerprint: '${device.fingerprint}',\n    source: 'seed',\n  },`,
    )
    .join('\n')
  const qrs = sample.qrTexts.map((text) => `  '${text}',`).join('\n')
  return `// Generated by \`npm run seed:municipal\` (scripts/seed/municipal.ts) from
// src/data/seed/municipalSource.ts. Don't edit by hand; run it again instead.
//
// Four pre-made, signed barangay QRs for the municipal laptop demo: invented,
// de-identified counts for San Isidro Demo (synthetic sample data). Each was
// signed with a key pair made in memory for that run; only the public keys
// are kept, as pairedDevices seed rows. No private key is in this repo.
import type { SampleDevice } from './municipalSource'

export const MUNICIPAL_SAMPLE_EPI_WEEK = '${sample.epiWeek}'

export const municipalSampleDevices: SampleDevice[] = [
${devices}
]

export const municipalSampleQrTexts: string[] = [
${qrs}
]
`
}
