// Generated by `npm run seed:municipal` (scripts/seed/municipal.ts) from
// src/data/seed/municipalSource.ts. Don't edit by hand; run it again instead.
//
// Four pre-made, signed barangay QRs for the municipal laptop demo: invented,
// de-identified counts for San Isidro Demo (synthetic sample data). Each was
// signed with a key pair made in memory for that run; only the public keys
// are kept, as pairedDevices seed rows. No private key is in this repo.
import type { SampleDevice } from './municipalSource'

export const MUNICIPAL_SAMPLE_EPI_WEEK = '2026-W41'

export const municipalSampleDevices: SampleDevice[] = [
  {
    barangay: 'SID-BGS',
    publicJwk: { kty: 'EC', crv: 'P-256', x: 'ykBFH4G3pP0C0KImEvwFXrI3BPFFgQ7vebyXuwpA6Zg', y: 'UWOgMNlbg33QEzgXiiGmaLPHZEVdhLriIUWfJ0BUrxI' },
    fingerprint: '0949-6322-55FB-5095',
    source: 'seed',
  },
  {
    barangay: 'SID-STN',
    publicJwk: { kty: 'EC', crv: 'P-256', x: '5g-5JQ0_fW2k3FUXwRuzKLNj3LWEevIPyr6Q539qz94', y: '8aVUqlCehKtnhBsl7pnAez-vKZk6animSxK1ycgUe5w' },
    fingerprint: '8AB3-B601-D128-E1C8',
    source: 'seed',
  },
  {
    barangay: 'SID-MAB',
    publicJwk: { kty: 'EC', crv: 'P-256', x: 'Az15YxLM1vkkE35Bkuh5G360vXK9Ey4BLNLCClvIaZs', y: 'Nd2VMDFEt2VoZZCbV1iyyVf4X0uhzEkAUXIIPTCNzy8' },
    fingerprint: 'DFEF-41BC-40F5-302B',
    source: 'seed',
  },
  {
    barangay: 'SID-RIV',
    publicJwk: { kty: 'EC', crv: 'P-256', x: 'br1UWJ-XHFOy2vAFFblVi3h4GrPzhgcYqNV8PM7yWcI', y: 'PGdzoUWVIx6z3UZgS87KJlpRUoWzWaRya61fyP9m9x8' },
    fingerprint: '4574-D5B0-EE32-DBC7',
    source: 'seed',
  },
]

export const municipalSampleQrTexts: string[] = [
  'AGP1.eyJ2IjoxLCJtIjoiU0lEIiwiYiI6IlNJRC1CR1MiLCJ3ayI6IjIwMjYtVzQxIiwibiI6MywiZSI6WyI8NSIsNiwxNCwzOCw3MSwxMl0sInciOjYsImYiOlswLDAsMF0sInUiOjAsImQiOjEwLCJ4IjowLCJyIjoxMn0.jfZLYRFtJC_tSwR7XNpNgzYAWaNBM_N4oZS4wcovogEREd-2isw_wLviKs3dqzS8gUYt5src-0Z7U3LuTlga_w',
  'AGP1.eyJ2IjoxLCJtIjoiU0lEIiwiYiI6IlNJRC1TVE4iLCJ3ayI6IjIwMjYtVzQxIiwibiI6MiwiZSI6WzAsIjw1Iiw2LDE1LDMzLDddLCJ3IjowLCJmIjpbMCwwLDBdLCJ1IjowLCJkIjo2MCwieCI6MCwiciI6NX0.OyZIAp-YNVDYuEKzEFHO_AFlCnbQAQVwZ7SfepdhlgsDvZUA-4wUgIs5m8jHaFKPwS8Q7JXyTflBW_FvZRZpPQ',
  'AGP1.eyJ2IjoxLCJtIjoiU0lEIiwiYiI6IlNJRC1NQUIiLCJ3ayI6IjIwMjYtVzQxIiwibiI6NCwiZSI6WzAsMCwiPDUiLDksMjEsIjw1Il0sInciOjAsImYiOlswLDAsMF0sInUiOjAsImQiOjI0LCJ4IjowLCJyIjoiPDUifQ._rKgiNS91_WF5B25uUhiB77gcZVgu5dgTrrBNWLNqIO4oljxmbvGBfO8nJrUxZJBNyoFDwywbFOwvX9_uOK5bg',
  'AGP1.eyJ2IjoxLCJtIjoiU0lEIiwiYiI6IlNJRC1SSVYiLCJ3ayI6IjIwMjYtVzQxIiwibiI6MiwiZSI6WzAsMCwwLCI8NSIsIjw1IiwwXSwidyI6MCwiZiI6WzAsMCwwXSwidSI6MCwiZCI6NTAsIngiOjMwLCJyIjowfQ.zO-5hEfSjc_pWSGyQ2sAxzPFsV7UqcQWDQiFA8MolA71pCEwEKVc_ebg_ukZBuhRsIThT5MiWdZsMyooaoEp9w',
]
