import { expect, test } from '@playwright/test'
import { generateDeviceKeyPair } from '../src/qr/sign'
import { encodeReturn, type ReturnPacket } from '../src/qr/return'
import { openPage } from './lock'

test('return receipt refuses wrong recipient and changed keys, preserves duplicates, and resets', async ({ page, context }) => {
  const keys = await generateDeviceKeyPair()
  const base: ReturnPacket = { version: 1, approvalId: 'browser-return', municipality: 'SID', barangay: 'SID-MAL', epiWeek: '2026-W41', approvedAt: '2026-10-09T08:00:00.000Z', approver: 'Municipal health officer', actions: [{ kind: 'doctor-team', barangay: 'SID-MAL', watchCount: '<5' }], publicJwk: keys.publicJwk }
  const text = await encodeReturn(base, keys.privateKey)
  await openPage(page, '/receive')
  await expect(page.locator('html')).toHaveAttribute('data-shell-status', 'ready')
  await page.waitForFunction(() => !!navigator.serviceWorker.controller)
  await context.setOffline(true)
  const verify = async (value: string) => {
    await page.getByLabel('Or paste the QR text', { exact: true }).fill(value)
    await page.getByRole('button', { name: 'Check the pasted text' }).click()
  }
  await verify(text.replace('AGPR1.', 'AGPR2.'))
  await expect(page.getByRole('alert')).toContainText('unsupported')
  await verify(await encodeReturn({ ...base, barangay: 'SID-BGS', actions: [{ kind: 'doctor-team', barangay: 'SID-BGS', watchCount: 6 }] }, keys.privateKey))
  await expect(page.getByRole('alert')).toContainText('another barangay')
  await verify(text)
  await expect(page.getByRole('button', { name: /^Save on this phone/ })).toBeDisabled()
  await expect(page.getByRole('region', { name: 'Approved instructions' })).toContainText('<5 residents')
  await page.getByRole('button', { name: 'Cancel preview' }).click()
  await verify(text)
  // The check row (CheckRow) is the target: its label, around the checkbox.
  const matches = page.getByRole('checkbox', { name: 'The fingerprint matches the RHU laptop' })
  await expect(matches).not.toBeChecked()
  await page.locator('label').filter({ has: matches }).click()
  await expect(matches).toBeChecked()
  await page.getByRole('button', { name: /^Save on this phone/ }).click()
  await expect(page.getByRole('heading', { name: 'Instructions saved on this phone' })).toBeVisible()
  // 1g: back on Home the row shows as just received (with its text twin) for
  // this visit, and opens the instructions sheet, times in the app's format.
  await page.getByRole('link', { name: /^Back to Home/ }).click()
  const row = page.getByRole('button', { name: /^Instructions from the RHU/ })
  await expect(row).toContainText('Received just now · 1 action')
  await expect(page.getByRole('status').filter({ hasText: 'Instructions from the RHU saved on this phone.' })).toHaveCount(1)
  await row.click()
  const sheet = page.getByRole('dialog', { name: 'Approved instructions for Maligaya-D' })
  await expect(sheet).toContainText('<5 residents')
  await expect(sheet).toContainText(/Week 2026-W41 · Municipal health officer · approved (Mon|Tue|Wed|Thu|Fri|Sat|Sun), [A-Z][a-z]{2} \d{1,2}, \d{1,2}:\d{2} (AM|PM)/)
  await sheet.getByRole('button', { name: 'Close' }).click()
  await expect(sheet).toHaveCount(0)
  await openPage(page, '/receive')
  await verify(text)
  await expect(page.getByRole('checkbox')).toHaveCount(0)
  await page.getByRole('button', { name: /^Save on this phone/ }).click()
  await expect(page.getByRole('heading', { name: 'Already saved on this phone' })).toBeVisible()
  await openPage(page, '/receive')
  const changed = await generateDeviceKeyPair()
  await verify(await encodeReturn({ ...base, publicJwk: changed.publicJwk }, changed.privateKey))
  await expect(page.getByRole('alert')).toContainText('key changed')
  await verify(await encodeReturn({ ...base, approvalId: 'old', approvedAt: '2026-10-08T08:00:00.000Z' }, keys.privateKey))
  await page.getByRole('button', { name: /^Save on this phone/ }).click()
  await expect(page.getByRole('alert')).toContainText('older')
  // Use the app's production reset, then check the UI and persisted metadata.
  await openPage(page, '/device')
  page.once('dialog', (dialog) => void dialog.accept())
  await page.getByRole('button', { name: 'Reset sample data', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: "Sample data reset to today's dates." })).toBeVisible()
  // Without saved instructions, Home has no instructions row, only the link.
  await openPage(page, '/')
  await expect(page.getByRole('heading', { level: 2, name: /^Today, / })).toBeVisible({ timeout: 30_000 })
  await expect(page.getByRole('link', { name: 'Got a QR from the RHU? Scan it' })).toBeVisible()
  await expect(page.getByRole('button', { name: /^Instructions from the RHU/ })).toHaveCount(0)
  await openPage(page, '/receive')
  await verify(text)
  await expect(page.getByRole('checkbox')).toHaveCount(0)
  await openPage(page, '/device')
  page.once('dialog', (dialog) => void dialog.accept())
  await page.getByRole('button', { name: 'Reset sample data and pairing', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Sample data and pairing reset.' })).toBeVisible()
  await openPage(page, '/receive')
  await verify(text)
  await expect(page.getByRole('checkbox', { name: 'The fingerprint matches the RHU laptop' })).toBeVisible()
})
