import { expect, test } from '@playwright/test'
import { generateDeviceKeyPair } from '../src/qr/sign'
import { encodeReturn, type ReturnPacket } from '../src/qr/return'
import { openPage } from './lock'

test('return receipt refuses wrong recipient and changed keys, preserves duplicates, and resets', async ({ page, context }) => {
  const keys = await generateDeviceKeyPair()
  const base: ReturnPacket = { version: 1, approvalId: 'browser-return', municipality: 'SID', barangay: 'SID-MAL', epiWeek: '2026-W41', approvedAt: '2026-10-09T08:00:00.000Z', approver: 'Municipal health officer', actions: [{ kind: 'doctor-team', barangay: 'SID-MAL', watchCount: '<5' }], publicJwk: keys.publicJwk }
  const text = await encodeReturn(base, keys.privateKey)
  await openPage(page, '/receive')
  await expect(page.locator('html')).toHaveAttribute('data-shell-status', 'ready')
  await page.waitForFunction(() => !!navigator.serviceWorker.controller)
  await context.setOffline(true)
  const verify = async (value: string) => {
    await page.getByLabel('Return QR text', { exact: true }).fill(value)
    await page.getByRole('button', { name: 'Verify return QR' }).click()
  }
  await verify(text.replace('AGPR1.', 'AGPR2.'))
  await expect(page.getByRole('alert')).toContainText('unsupported')
  await verify(await encodeReturn({ ...base, barangay: 'SID-BGS', actions: [{ kind: 'doctor-team', barangay: 'SID-BGS', watchCount: 6 }] }, keys.privateKey))
  await expect(page.getByRole('alert')).toContainText('another barangay')
  await verify(text)
  await expect(page.getByRole('button', { name: 'Save instructions on this phone' })).toBeDisabled()
  await expect(page.getByRole('region', { name: 'Approved instructions' })).toContainText('<5 residents')
  await page.getByRole('button', { name: 'Cancel preview' }).click()
  await verify(text)
  await expect(page.getByRole('checkbox', { name: 'The fingerprint matches the RHU laptop' })).not.toBeChecked()
  await page.getByRole('checkbox', { name: 'The fingerprint matches the RHU laptop' }).check()
  await page.getByRole('button', { name: 'Save instructions on this phone' }).click()
  await expect(page.getByRole('heading', { name: 'Instructions saved on this phone' })).toBeVisible()
  await openPage(page, '/receive')
  await verify(text)
  await expect(page.getByRole('checkbox')).toHaveCount(0)
  await page.getByRole('button', { name: 'Save instructions on this phone' }).click()
  await expect(page.getByRole('heading', { name: 'Already saved on this phone' })).toBeVisible()
  await openPage(page, '/receive')
  const changed = await generateDeviceKeyPair()
  await verify(await encodeReturn({ ...base, publicJwk: changed.publicJwk }, changed.privateKey))
  await expect(page.getByRole('alert')).toContainText('key changed')
  await verify(await encodeReturn({ ...base, approvalId: 'old', approvedAt: '2026-10-08T08:00:00.000Z' }, keys.privateKey))
  await page.getByRole('button', { name: 'Save instructions on this phone' }).click()
  await expect(page.getByRole('alert')).toContainText('older')
  // Use the app's production reset, then check the UI and persisted metadata.
  await openPage(page, '/device')
  page.once('dialog', (dialog) => void dialog.accept())
  await page.getByRole('button', { name: 'Reset sample data', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: "Sample data reset to today's dates." })).toBeVisible()
  await openPage(page, '/')
  await expect(page.getByRole('region', { name: 'Approved instructions' })).toHaveCount(0)
  await openPage(page, '/receive')
  await verify(text)
  await expect(page.getByRole('checkbox')).toHaveCount(0)
  await openPage(page, '/device')
  page.once('dialog', (dialog) => void dialog.accept())
  await page.getByRole('button', { name: 'Reset sample data and pairing', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Sample data and pairing reset.' })).toBeVisible()
  await openPage(page, '/receive')
  await verify(text)
  await expect(page.getByRole('checkbox', { name: 'The fingerprint matches the RHU laptop' })).toBeVisible()
})
